/**
 * ActionExecutor.js
 *
 * Dispatches action objects (produced by the Planner) to the correct tool.
 *
 * Architecture position:
 *   Planner → action[] → ActionExecutor → Tools → Playwright
 *
 * Key additions in V2:
 *   Field Registry — a Map<string, Locator> populated lazily when a
 *   DETECT_FIELD step runs. Subsequent FILL/CLICK steps reference fields by
 *   name instead of carrying a Playwright Locator in the plan object, keeping
 *   plans as pure data that can be serialised, logged, or generated by an LLM.
 *
 * Backward compatibility:
 *   Actions that previously required a raw `locator` property still work.
 *   If `locator` is present it is used directly; `field` is the new alternative.
 */

import { ACTION_TYPES } from '../config/constants.js';
import logger from '../utils/logger.js';

export class ActionExecutor {
  /**
   * @param {import('./Agent.js').Agent} agent - Fully-initialised agent instance.
   */
  constructor(agent) {
    this._agent = agent;

    /**
     * Maps semantic field names ('name', 'description', …) to Playwright
     * Locators.  Populated the first time a DETECT_FIELD step executes.
     * @type {Map<string, import('playwright').Locator>}
     */
    this._fieldRegistry = new Map();

    /** Set to true after the first full FormDetection scan. */
    this._fieldsScanned = false;
  }

  // ---------------------------------------------------------------------------
  // Public API
  // ---------------------------------------------------------------------------

  /**
   * Execute a single action descriptor.
   *
   * @param {object} action
   * @param {string} action.type          - One of ACTION_TYPES.
   * @param {string} [action.url]         - NAVIGATE: destination URL.
   * @param {string} [action.field]       - Semantic field name ('name', 'description', …).
   * @param {import('playwright').Locator} [action.locator] - Raw locator (legacy / direct use).
   * @param {string} [action.value]       - FILL / SEND_KEYS / VERIFY_FIELD: expected text.
   * @param {string} [action.label]       - SCREENSHOT: filename label.
   * @param {number} [action.pixels]      - SCROLL: distance in pixels.
   * @param {string} [action.direction]   - SCROLL: 'up' | 'down'.
   * @param {number} [action.ms]          - WAIT: duration in milliseconds.
   * @returns {Promise<any>}
   */
  async execute(action) {
    const { type } = action;

    switch (type) {

      // --- Navigation ---
      case ACTION_TYPES.NAVIGATE:
        return this._agent.navigation.navigateTo(action.url);

      case ACTION_TYPES.WAIT_FOR_IDLE:
        return this._agent.navigation.waitForNetworkIdle();

      // --- Intelligence: field registry ---
      case ACTION_TYPES.DETECT_FIELD:
        return this._detectField(action.field);

      case ACTION_TYPES.VERIFY_FIELD: {
        const locator = this._resolveLocator(action);
        return this._agent.validation.fieldHasValue(locator, action.value);
      }

      // --- Mouse ---
      case ACTION_TYPES.CLICK: {
        const locator = this._resolveLocator(action);
        return this._agent.click.click(locator);
      }

      case ACTION_TYPES.DOUBLE_CLICK: {
        const locator = this._resolveLocator(action);
        return this._agent.click.doubleClick(locator);
      }

      // --- Keyboard ---
      case ACTION_TYPES.FILL: {
        const locator = this._resolveLocator(action);
        return this._agent.input.fill(locator, action.value);
      }

      case ACTION_TYPES.SEND_KEYS: {
        const locator = this._resolveLocator(action);
        return this._agent.input.sendKeys(locator, action.value);
      }

      // --- Page movement ---
      case ACTION_TYPES.SCROLL:
        if (action.direction === 'up') {
          return this._agent.scroll.scrollUp(action.pixels);
        }
        return this._agent.scroll.scrollDown(action.pixels);

      // --- Utilities ---
      case ACTION_TYPES.SCREENSHOT:
        return this._agent.screenshot.capture(action.label || '');

      case ACTION_TYPES.WAIT:
        return new Promise((resolve) => setTimeout(resolve, action.ms || 1000));

      default:
        logger.warn(`Unknown action type: "${type}" — skipping`);
        return null;
    }
  }

  /**
   * Execute an ordered list of actions sequentially, logging each step number.
   * Stops immediately if any action throws.
   *
   * @param {object[]} actions
   * @returns {Promise<any[]>} Results of each action in order.
   */
  async executeAll(actions) {
    const results = [];
    const total = actions.length;

    for (let i = 0; i < total; i++) {
      const action = actions[i];
      logger.plan(`[${i + 1}/${total}] ${action.type}${action.field ? ` → "${action.field}"` : ''}`);
      results.push(await this.execute(action));
    }

    return results;
  }

  // ---------------------------------------------------------------------------
  // Field registry helpers
  // ---------------------------------------------------------------------------

  /**
   * Ensure the field registry is populated, then return the locator for
   * the named field (or null if it could not be found on the page).
   *
   * The FormDetectionService scan is expensive (multiple DOM queries), so it
   * is only triggered once regardless of how many DETECT_FIELD steps appear
   * in the plan.
   *
   * @param {string} fieldName - Semantic field name.
   * @returns {Promise<import('playwright').Locator|null>}
   */
  async _detectField(fieldName) {
    if (!this._fieldsScanned) {
      logger.observe('Field registry empty — running FormDetectionService scan');
      const detected = await this._agent.formDetection.detectFields();

      for (const [key, locator] of Object.entries(detected)) {
        this._fieldRegistry.set(key, locator);
      }
      this._fieldsScanned = true;

      logger.observe(
        `Field registry populated — keys: [${[...this._fieldRegistry.keys()].join(', ')}]`,
      );
    }

    const locator = this._fieldRegistry.get(fieldName);
    if (locator) {
      logger.verify(`Registry: "${fieldName}" → resolved ✓`);
    } else {
      logger.warn(`Registry: "${fieldName}" not found after scan`);
    }

    return locator;
  }

  /**
   * Resolve a Playwright Locator from an action descriptor.
   * Prefers an explicit `locator` property (backward compat) then falls
   * back to looking up `field` in the registry.
   *
   * @param {object} action
   * @returns {import('playwright').Locator}
   */
  _resolveLocator(action) {
    if (action.locator) return action.locator;   // legacy / direct use

    if (!action.field) {
      throw new Error(
        `ActionExecutor: action "${action.type}" has neither locator nor field. ` +
        'Provide one or include a DETECT_FIELD step before this action.',
      );
    }

    const locator = this._fieldRegistry.get(action.field);
    if (!locator) {
      throw new Error(
        `ActionExecutor: field "${action.field}" not in registry. ` +
        `Did you include a DETECT_FIELD step for "${action.field}" before this action?`,
      );
    }

    return locator;
  }
}
